# Generated by Django 4.1 on 2022-09-10 12:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bloguser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='phone',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='idcard',
            field=models.CharField(error_messages={
                                   'unique': '身份证格式不正确'}, max_length=18, unique=True, verbose_name='idcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloguser',
            name='mobile',
            field=models.CharField(blank=True, error_messages={
                                   'unique': '手机号格式不正确'}, help_text='仅限11位数字', max_length=11, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='name',
            field=models.CharField(error_messages={'unique': '姓名已存在'}, max_length=10, unique=True, validators=[
                                   django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloguser',
            name='photo',
            field=models.ImageField(
                height_field=150, upload_to='', verbose_name='photo', width_field=100),
            preserve_default=False,
        ),
    ]
